version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # These match the DATABASES setting in your settings.py
      POSTGRES_DB: fyp_identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dt1026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    command: gunicorn identity_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: