services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: fyp_identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dt1026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    env_file:
      - .env
    command: gunicorn identity_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: